#!/bin/zsh
scriptDir="${0:A:h}"
cd $scriptDir
# cd /Users/sa/side-projects/thewhaleproject.github.io
# localhost:8000
python3 -m http.server 8000 & \
    fswatch -l 1 --event "Created" -o $scriptDir | xargs -n1 -I {} \
    osascript -e 'tell application "Google Chrome" to tell the active tab of its first window to reload'
